services:
    - docker
dist: focal
if: tag IS present
script:
    - docker pull veyon/docbuilder:latest || docker build -t veyon/docbuilder:latest ${TRAVIS_BUILD_DIR}
    - docker run -v ${TRAVIS_BUILD_DIR}:/docs:rw -w /docs veyon/docbuilder:latest /docs/build-manuals.py
deploy:
    provider: releases
    api_key:
        secure: "aYcLIKSJVe241DV4LgBOstAK1WTwEREeAxOCs3J1zYAJNfjDlg3JEyx4XaIAy+Qh04ulIMnoerr9su1UQ9/7urBALde6Kf6ecXAgGLprhZ+C8Qz7fL2rlSKCg/e0e9FVBP8TGoIggn8fZWKTm3pr0xClBUmfvoj9qwZoTB1rXqv3QNuObQOMnVsHuR9F5WxotLzFKz70g9u/7DW4amoGlIqyODYvaQbt6AOuNbubeBfpH2eSj0f/EBtxPZdz74WeY10QpptP7xSDBgqzKOxBvAeXAaHl3nU2ROx8xfgrYSNHbvcyxeVIUoGIQs/ERGRKNBXWD9EnRLCHctlW+uwlaXB0kFgncW5251QebK39FRm/NOTZtmq1gI7O5RoP6wlhJyk22Z6UrLyiiM97JPVYTs2UmoJpXbF5s5tRGibCUcFgzdy30M2dElrtJ3LsyWwi/7MKoSVq3bMv8cVtkkUJW+O/FxAwo8RqoipvrIERUyAPVS6kHa6YLf2kV9OfbBUmTSOe8ux92jdVrCiyj50wf5564GrY//oqFFDa9jsKa3WaA/8yHx6Q2GZ0h+/mYqwrLRTLz3BllCCpIeP53bFTkJ9jvy9CP6g+0nJhKwEJEIQDTbf5CbBUUFxCxptYRYv5diRQBBNUUshHLEMyjoOS9lqqZZvgCe2/OBGEGQekK3o="
    repo: veyon/docs
    skip_cleanup: true
    file_glob: true
    file: "veyon*.pdf"
    on:
        tags: true
        all_branches: true
