services:
    - docker
dist: xenial
script:
    - docker pull veyon/docbuilder:latest || docker build -t veyon/docbuilder:latest ${TRAVIS_BUILD_DIR}
    - docker run -v ${TRAVIS_BUILD_DIR}:/docs:rw -w /docs veyon/docbuilder:latest /docs/build-manuals.py
deploy:
    provider: releases
    api_key:
        secure: Eon42gDI4nidkS1o57xy0DyAzlE7QjTd0ms17XgtXgsij4SabDwvX/M4Hru7TZNu9KWH6F5rAxgovlykX4xqhdKjaACCWsbs+OnWXAujnvYMA9uAGrslBy/nARZeY70EnN1mObCpTUyD1BuV1UBdg0MqaIqMMwJz5Zg7TC2s3H83uqt3x6Eio354RokwGBSd5t9GmnBIciW11Nl8wVVDN7Mt8mHyUXLWc1Upjz8jO/rzjxAsovGipIYpKtCNpGUgGqyMc0OgqkEnmVqWzkaEYBzbHh7Z/irb+KQBJOBjC6Plx3TwkIPsPdDRbBnhH50nHuElhx3PlNLbWMnNS+KOWJxLKfit2uBp/RnYkLnn91iA3Jf4d94/oDHL0ylvbbn8CBYUWmKzrWNx9eX9I1zTX/UhmFHaWLS6t5sAAIBEUo1C6Mgp/UTi9F2NhbC+HaB+IFEKWV5P4jYL/0IWePOcH7pk6k4VUg77EsXdVsD6yKuy2k8DWL6JJ5y2YoDO1B4HSdWcOasV2+SCyZlO6qRepgVTQZ2H/ckciEjN3V728o1VP4qybiDHi0tXitIxnSOI+ARtA4X7Ai9NLfRpHGUlD/OmTvL36znuFNnyB6eFom3meurO9vo1DUnWjRTVUaUhQwZ1Nq6CjD52AZSHJMQOkLRZi2fNvFm9/56bwRszMD8=
    repo: veyon/docs
    skip_cleanup: true
    file_glob: true
    file: "veyon*.pdf"
    on:
        tags: true
        all_branches: true
